markdown: kramdown
permalink: /:categories/:year/:month/:day/:title 
url: http://jasongj.github.io
name: jun
author: jun
qq: 994705904
email: guojjason@gmail.com
duoshuo: jasongj
# beian: 
# cnzz: guojjason@gmail.com
weibo: guojjason@gmail.com
github: jasongj
pygments: true
safe: true
paginate: 20
about: "test"
